---
output: html_document
---

### Reading the activitie file
```{r}
activities <- read.table("UCI HAR Dataset/activity_labels.txt")
activities[,2] <- as.character(activities[,2])
head(activities)
```
### Reading the features file and extracting mean and std variables
```{r}
features <- read.table("UCI HAR Dataset/features.txt")
features[,2] <- as.character(features[,2])
extractredFeatures <- grep(".*mean.*|.*std.*", features[,2])
extractredFeatures.names <- features[extractredFeatures,2]
extractredFeatures.names <- gsub('-mean', 'Mean', extractredFeatures.names)
extractredFeatures.names <- gsub('-std', 'Std', extractredFeatures.names)
extractredFeatures.names <- gsub('[-()]', '', extractredFeatures.names)
extractredFeatures.names
```
### Loading, Merging data sets and labeling the variables. Using descriptive activity names in resulting data set
```{r}
library(plyr)
traindata <- read.table("UCI HAR Dataset/train/X_train.txt")[extractredFeatures]
trainActivities <- read.table("UCI HAR Dataset/train/Y_train.txt")
trainSubjects <- read.table("UCI HAR Dataset/train/subject_train.txt")
traindataset <- cbind(trainSubjects, trainActivities, traindata)
testdata <- read.table("UCI HAR Dataset/test/X_test.txt")[extractredFeatures]
testActivities <- read.table("UCI HAR Dataset/test/Y_test.txt")
testSubjects <- read.table("UCI HAR Dataset/test/subject_test.txt")
testdataset <- cbind(testSubjects, testActivities, testdata)
finaldata <- rbind(traindataset, testdataset)
colnames(finaldata) <- c("subject", "activity", extractredFeatures.names)
finaldata$activity <- mapvalues(finaldata$activity, from=as.character(activities[,1]), to=as.character(activities[,2]))
finaldata$activity <- as.factor(finaldata$activity)
head(finaldata)
```
### Averaging data for subject, activity and variable into tidy data set
```{r}
library(reshape2)
library(dplyr)
finaldata.melted <- melt(finaldata, id = c("subject", "activity"))
groupeddata <- group_by(finaldata.melted, subject,activity,variable)
summarydata <- summarize(groupeddata, avg = mean(value, na.rm = T))
head(summarydata)
```